"""add fields to professionals

Revision ID: bf2fe67cc5b6
Revises: 6dcf5f99936e
Create Date: 2026-04-11 08:58:48.828257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bf2fe67cc5b6'
down_revision: Union[str, None] = '6dcf5f99936e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professionals', sa.Column('date_of_birth', sa.DateTime(), nullable=False))
    op.add_column('professionals', sa.Column('state_of_origin', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('professionals', sa.Column('local_government', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('professionals', sa.Column('current_city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('professionals', sa.Column('professional_body_membership_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('professionals', sa.Column('no_professional_body_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('professionals', sa.Column('certification_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professionals', 'certification_url')
    op.drop_column('professionals', 'no_professional_body_reason')
    op.drop_column('professionals', 'professional_body_membership_url')
    op.drop_column('professionals', 'current_city')
    op.drop_column('professionals', 'local_government')
    op.drop_column('professionals', 'state_of_origin')
    op.drop_column('professionals', 'date_of_birth')
    # ### end Alembic commands ###
