"""add indexes unique constraints and profile image

Revision ID: e8d1cb6e3be5
Revises: 301034b4ff3c
Create Date: 2026-04-03 05:23:16.366110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e8d1cb6e3be5'
down_revision: Union[str, None] = '301034b4ff3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_unique_constraint(None, 'payments', ['provider_ref'])
    op.create_index(op.f('ix_portfolios_moderation_status'), 'portfolios', ['moderation_status'], unique=False)
    op.create_index(op.f('ix_professionals_service_area'), 'professionals', ['service_area'], unique=False)
    op.create_index(op.f('ix_professionals_subscription_plan'), 'professionals', ['subscription_plan'], unique=False)
    op.create_index(op.f('ix_professionals_trade_category'), 'professionals', ['trade_category'], unique=False)
    op.create_index(op.f('ix_professionals_verification_status'), 'professionals', ['verification_status'], unique=False)
    op.create_unique_constraint(None, 'professionals', ['nin'])
    op.add_column('users', sa.Column('profile_image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_column('users', 'profile_image_url')
    op.drop_constraint(None, 'professionals', type_='unique')
    op.drop_index(op.f('ix_professionals_verification_status'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_trade_category'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_subscription_plan'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_service_area'), table_name='professionals')
    op.drop_index(op.f('ix_portfolios_moderation_status'), table_name='portfolios')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    # ### end Alembic commands ###
